### ISSUE TITLE
Missing escape of dollar sign in Powershell snippet

### ISSUE THREAD

**Issue by ztrhgf** [ryanolsonx/snippet-creator#1]
Hi,
could you please escape dollar sign in powershell snippets? So replace it for $$ or \\$. Without this edit it is useless for powershell, thanks :)

Or maybe use some of these tips https://stackoverflow.com/questions/3215705/escaping-the-character-in-snippets/43427442#43427442

I think edit would go here:
function createBody(code) {
  return code.replace(/\t/g, '\\t').split('\n');
}

**Comment by ryanolsonx** [comment]
That's a really good idea. I'll dig into it.

**Comment by ryanolsonx** [comment]
You should see an update in VS Code sometime today. 🎉

**Comment by ztrhgf** [comment]
Tomorrow I will try it and let you know. Thank you very much for your work
:-)

**Comment by ryanolsonx** [comment]
Definitely let me know if you find any issues with it. I created some tests in the project to capture all of the cases I'm covering. I just don't know much about powershell.

**Comment by ztrhgf** [comment]
Hi,
it works perfectly now! I edited my review.

Thank you so much
O.

út 14. 5. 2019 v 21:38 odesílatel Ryan Olson <notifications@github.com>
napsal:
