### ISSUE TITLE
Escaping $ symbol when saving php snippets

### ISSUE THREAD

**Issue by sarkanytibor** [ryanolsonx/snippet-creator#6]
Hi Ryan!

I find this extension really cool! :-) 

I faced an issue however when I first wanted to save a few php lines using "snippet creator". In php --> variables are marked using $ symbol and after saving a function and recalling it from my snippets, all $ symbol is gone. _(edit: it could be escaped in js and html files as well, so basically every dollar symbol could be saved as $$ or \\$ in the json file)_

An example for this:

- saving this as for example"test"
`$count=1;
while($count < 100){
    echo "<li>$count</li>";
    $count++;
}`

- and recalling it will give this:
`count=1;
while(count < 100){
    echo "<li>count</li>";
    count++;
}`

Do you know maybe what causes this? Thank you very much for your help, your extension is btw the best thing I have ever found :-)

**Comment by ryanolsonx** [comment]
Good call.  I'll investigate this later tonight and put out an update with a fix :)

**Comment by ryanolsonx** [comment]
An update should come to your VS Code today :D

**Comment by sarkanytibor** [comment]
Hi Ryan! Yes, it works perfectly, thank you very much! :-)

If you will have the time, please consider extending $ sign support to js as well. (jquery variables use $ symbol for example) But maybe it shouldn't be language specific, so basically everywhere every $ symbol could be escaped.

Btw I am really grateful to you for making this extension, I can now concentrate on the interesting part, without writing the same things again and again. So I just can't tell you how fantastic this extension is. Thank you very much :-)

**Comment by ryanolsonx** [comment]
Thanks for all of your compliments.  I'm glad it's helping you.  I created this because I hated manually creating snippets and splitting strings into arrays for the syntax.

> But maybe it shouldn't be language specific, so basically everywhere every $ symbol could be escaped.

Good idea!  I'll do another update.
